export const stepVData = {
english:{
    header:"VPN Setup",
    title:"How to connect using VPN software",
    badgeValue:"Step 5",
    p1:"To connect to the corporate network by using VPN software on your computer:",
    p2:"1. Make sure your computer is connected to the Internet and you can see various web pages.",
    p3:"2. Double-click on the VPN application icon",
    p3_e:"at the bottom-right corner of the screen.The Cisco AnyConnect application window appears.",
    p4:"3. Type the following into the blank field in the application window: <b>vpn.cpg-gpc.ca</b>",
    p5:"4. Click <b>Connect</b>. A prompt for a username and password will appear within 30 seconds.",
    p6:"5. Type your username in the following format: <b>cpg-gpc\\userID</b> (enter the same userID that you use to log in to your computer)",
    p7:"6. Type the same password that you use to log into your computer at work.",
    p8:"7. Click <b>OK.</b> The message “VPN: Connected to vpn.cpg-gpc.ca” appears.",
    p9:"8. VPN icon will also display a padlock",
    p9_e:"to indicate secure connection to VPN.",
    footer_text:
      "If you encounter any issues completing this step, please contact our Computer Refresh team for support: ",
    footer_link_text: "Computer.Refresh@innovapost.com",
    footer_link_path: "Computer.Refresh@innovapost.com",
    btnInfo: [
        { to: "/step4", text: "Previous: Step 4" },
        { to: "/", text: "Homepage" },
        { to: "/step6", text: "Step 6" },
      ],
},
french:{
  header:"Vérification du client RPV Cisco",
    title:"Comment se connecter à l'aide du logiciel pour RPV",
    badgeValue:"Étape 5",
    p1:"Pour se connecter au réseau de la Société en utilisant le logiciel pour RPV sur votre ordinateur :",
    p2:"1. Assurez-vous que votre ordinateur est connecté à Internet et que vous pouvez afficher diverses pages Web.",
    p3:"2. Faites un double-clic sur l'icône du logiciel pour RPV ",
    p3_e:"qui s'affiche dans le coin inférieur droit de l'écran. La fenêtre de l'application AnyConnect de Cisco s'affiche.",
    p4:"3. qui s'affiche dans le coin inférieur droit de l'écran.La fenêtre de l'application AnyConnect de Cisco s'affiche. <b>vpn.cpg-gpc.ca</b>",
    p5:"4. Cliquez sur le bouton <b>Connexion</b>. Une fenêtre s'affiche dans un délai de 30 secondes et vous demande de saisir un code d'utilisateur et un mot de passe.",
    p6:"5. Tapez votre code d'utilisateur en suivant ce format :  <b>cpg-gpc\\code d'utilisateur</b> (saisissez le même nom d'utilisateur que celui que vous utilisez pour ouvrir une session dans votre ordinateur)",
    p7:"6. Tapez le même mot de passe que vous utilisez pour accéder à votre ordinateur au bureau.",
    p8:"7. Cliquez sur <b>OK.</b> Le message suivant s'affiche : « VPN: Connected vpn.cpg-gpc.ca ».",
    p9:"8. L'icône du RPV affiche aussi un cadenas pour indiquer qu'il s'agit d'une connexion sécurisée au RPV.",
    footer_text:
    "Si vous éprouvez des difficultés avec cette étape, écrivez à l’adresse",
  footer_link_text: "Computer.Refresh@innovapost.com",
  footer_link_path: "Computer.Refresh@innovapost.com",
  footer_link_text_e:"pour obtenir de l’aide.",
    btnInfo: [
        { to: "/step4", text: "Précédent : Étape 4" },
        { to: "/", text: "Page d'accueil" },
        { to: "/step6", text: "Étape 6" },
      ],
},
}
